### ISSUE TITLE
【Bounty】LatticeX Forum论坛BUG分析验证

### ISSUE THREAD

**Issue by biganxin** [LatticeX-Foundation/dev-bounties#3]
## 概述
社区反馈一个论坛bug，邀请社区伙伴进行测试定位。详细信息请联系 @biganxin 了解。

## 要求
完成复现并反馈原因和修复方案

## 奖励
1800LAT

## 报名和交付
报名：仅接收一位报名，本帖回复“报名”+交付时间+奖励接收地址+联系方式

交付：本帖回复交付内容/说明

**Comment by Re13orn** [comment]
报名
2022年1月17日
lat13d0ypn40vk6h8ltfqhxghlj8pk5y4zzet8ypdf
reborn.sec@gmail.com

**Comment by biganxin** [comment]
Excellent work~
It has been submitted to the Foundation for approval.
The award is expected to arrive in 7 working days.
Thank you for your support~

**Comment by biganxin** [comment]
@Re13orn 奖励已发放
